// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: physical.proto

package PhysicalTime_stc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncTime_GetTime_FullMethodName = "/SyncTime/GetTime"
)

// SyncTimeClient is the client API for SyncTime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncTimeClient interface {
	GetTime(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*TimeReply, error)
}

type syncTimeClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncTimeClient(cc grpc.ClientConnInterface) SyncTimeClient {
	return &syncTimeClient{cc}
}

func (c *syncTimeClient) GetTime(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*TimeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeReply)
	err := c.cc.Invoke(ctx, SyncTime_GetTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncTimeServer is the server API for SyncTime service.
// All implementations must embed UnimplementedSyncTimeServer
// for forward compatibility.
type SyncTimeServer interface {
	GetTime(context.Context, *TimeRequest) (*TimeReply, error)
	mustEmbedUnimplementedSyncTimeServer()
}

// UnimplementedSyncTimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncTimeServer struct{}

func (UnimplementedSyncTimeServer) GetTime(context.Context, *TimeRequest) (*TimeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTime not implemented")
}
func (UnimplementedSyncTimeServer) mustEmbedUnimplementedSyncTimeServer() {}
func (UnimplementedSyncTimeServer) testEmbeddedByValue()                  {}

// UnsafeSyncTimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncTimeServer will
// result in compilation errors.
type UnsafeSyncTimeServer interface {
	mustEmbedUnimplementedSyncTimeServer()
}

func RegisterSyncTimeServer(s grpc.ServiceRegistrar, srv SyncTimeServer) {
	// If the following call pancis, it indicates UnimplementedSyncTimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncTime_ServiceDesc, srv)
}

func _SyncTime_GetTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncTimeServer).GetTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncTime_GetTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncTimeServer).GetTime(ctx, req.(*TimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncTime_ServiceDesc is the grpc.ServiceDesc for SyncTime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncTime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SyncTime",
	HandlerType: (*SyncTimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTime",
			Handler:    _SyncTime_GetTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "physical.proto",
}
